services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma_server
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data
    volumes:
      - ./data/chroma_db:/data
    restart: unless-stopped
    
  math-assistant:
    build: .
    container_name: math_assistant_app
    depends_on:
      - chromadb
      - qdrant

    env_file:
      - .env
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp-keys/ocr-stem-44aa72eb7fba.json
    volumes:
      - C:\gcp-keys:/gcp-keys
      - ./data:/app/data
      - ./data-samples:/app/data-samples
      - ./src:/app/src
      - ./tests:/app/tests
      - ./run_ingest.py:/app/run_ingest.py
      - ./chat.py:/app/chat.py


    ports:
      - "8080:8080"
    # Enable interactive CLI chat via TTY
    stdin_open: true
    tty: true
    # Run FastAPI server by default
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8080 --reload

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_server
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant_db:/qdrant/storage
    restart: unless-stopped

